_name_or_path:
    value: meta-llama/Llama-2-7b-hf
_wandb:
    value:
        cli_version: 0.23.1
        e:
            l5eumx9obnz7b1ryemsoihmckt15mh0z:
                args:
                    - --local_rank=0
                    - --deepspeed
                    - configs/ds_config_zero2_no_offload.json
                    - --full_finetune
                    - "False"
                    - --model_name_or_path
                    - meta-llama/Llama-2-7b-hf
                    - --seed
                    - "42"
                    - --data_seed
                    - "42"
                    - --base_dtype
                    - int4
                    - --adapter_dtype
                    - fp32
                    - --init_weights
                    - lava
                    - --lora_rank
                    - "128"
                    - --lora_alpha
                    - "16"
                    - --lora_dropout
                    - "0"
                    - --target_modules
                    - q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
                    - --data_path
                    - fxmeng/pissa-dataset
                    - --sub_task
                    - metamath:100000
                    - --dataset_split
                    - train
                    - --dataset_field
                    - instruction
                    - output
                    - --output_dir
                    - output/metamath-LAVA-r128-a16-B_int4-vib0.1-seed42
                    - --num_train_epochs
                    - "1"
                    - --model_max_length
                    - "512"
                    - --per_device_train_batch_size
                    - "2"
                    - --gradient_checkpointing
                    - "True"
                    - --gradient_accumulation_steps
                    - "8"
                    - --learning_rate
                    - "5e-5"
                    - --warmup_ratio
                    - "0.03"
                    - --lr_scheduler_type
                    - cosine
                    - --logging_steps
                    - "10"
                    - --save_strategy
                    - steps
                    - --save_steps
                    - "1000"
                    - --save_total_limit
                    - "1"
                    - --report_to
                    - wandb
                    - --optim
                    - adamw_torch
                    - --merge
                    - "False"
                    - --lambda_vib
                    - "0.1"
                    - --lambda_stab
                    - "1.0"
                    - --lambda_latent_stability
                    - "1.0"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1966736678912"
                        used: "1413680766976"
                email: yein0330@sogang.ac.kr
                executable: /home/dongwoo38/miniconda3/envs/pissa/bin/python3.10
                git:
                    commit: 4b4102dd787cd43bc1ec79fa604da20e8bec6b4f
                    remote: https://github.com/merrybabyxmas/lava2.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-1a133bd2-ae1e-86f3-56bf-38518f125ad4
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-6068f209-96d6-139d-80fb-7db74591f8b4
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-4f8fb1fe-e7c5-aad3-6f94-a16bee1178a0
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-760bf631-f8cc-ccc4-3350-5f6d4379dbe5
                host: user-WRX80-Creator
                memory:
                    total: "134894022656"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/dongwoo38/PiSSA/train.py
                python: CPython 3.10.19
                root: /home/dongwoo38/PiSSA
                startedAt: "2026-01-08T17:45:21.635635Z"
                writerId: l5eumx9obnz7b1ryemsoihmckt15mh0z
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 7
                - 13
                - 62
                - 66
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.45.1
            "9":
                "1": transformers_trainer
            "12": 0.23.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adapter_dtype:
    value: fp32
adapter_name_or_path:
    value: null
add_cross_attention:
    value: false
architectures:
    value:
        - LlamaForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
attn_implementation:
    value: flash_attention_2
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
base_dtype:
    value: int4
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bits:
    value: 16
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_path:
    value: fxmeng/pissa-dataset
data_seed:
    value: 42
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_field:
    value:
        - instruction
        - output
dataset_split:
    value: train
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: configs/ds_config_zero2_no_offload.json
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: null
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
full_finetune:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_size:
    value: 4096
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
init_weights:
    value: lava
initializer_range:
    value: 0.02
intermediate_size:
    value: 11008
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
lambda_latent_stability:
    value: 1
lambda_stab:
    value: 1
lambda_vib:
    value: 0.1
learning_rate:
    value: 5e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: output/metamath-LAVA-r128-a16-B_int4-vib0.1-seed42/runs/Jan09_02-45-05_user-WRX80-Creator
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lora_alpha:
    value: 16
lora_dropout:
    value: 0
lora_rank:
    value: 128
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 4096
max_steps:
    value: -1
merge:
    value: false
metric_for_best_model:
    value: null
min_length:
    value: 0
mlp_bias:
    value: false
model_max_length:
    value: 512
model_name_or_path:
    value: meta-llama/Llama-2-7b-hf
model_type:
    value: llama
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 32
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 32
num_key_value_heads:
    value: 32
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: output/metamath-LAVA-r128-a16-B_int4-vib0.1-seed42/lava_Llama-2-7b-hf_r128_a16.0_vb0.1_st1.0_ls1.0_bd-int4_ad-fp32_s42
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: meta-llama/Llama-2-7b-hf
            inference_mode: false
            peft_type: LAVA
            revision: null
            task_type: CAUSAL_LM
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 2
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
pretraining_tp:
    value: 1
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: bfloat16
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: false
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-05
rope_scaling:
    value: null
rope_theta:
    value: 10000
run_name:
    value: lava_Llama-2-7b-hf_r128_a16.0_vb0.1_st1.0_ls1.0_bd-int4_ad-fp32_s42
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 1000
save_strategy:
    value: steps
save_total_limit:
    value: 1
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
split_batches:
    value: null
sub_task:
    value:
        - metamath:100000
suppress_tokens:
    value: null
target_modules:
    value: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: bfloat16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.45.1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 32000
warmup_ratio:
    value: 0.03
warmup_steps:
    value: 0
weight_decay:
    value: 0
